### ISSUE TITLE
Bookkeeper fails to start if cookie already exists in zookeeper

### ISSUE THREAD

**Issue by stanfea** [onyx-platform/onyx-bookkeeper#5]
Bookkeeper fails to start if cookie already exists in zookeeper:

```
Caused by: org.apache.bookkeeper.bookie.BookieException$InvalidCookieException: org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists for /onyx/test/ledgers/cookies/xxx.xxx.xxx.xxx:3196
    at org.apache.bookkeeper.bookie.Bookie.checkEnvironment(Bookie.java:366)
    at org.apache.bookkeeper.bookie.Bookie.<init>(Bookie.java:466)
    at org.apache.bookkeeper.proto.BookieServer.newBookie(BookieServer.java:107)
    at org.apache.bookkeeper.proto.BookieServer.<init>(BookieServer.java:95)
    at org.apache.bookkeeper.proto.BookieServer.<init>(BookieServer.java:87)
    at onyx.state.bookkeeper.Bookie.start(bookkeeper.clj:35)
    at onyx.state.bookkeeper.BookieMonitor.start(bookkeeper.clj:71)
    at onyx.state.bookkeeper.BookieServers$fn__28021.invoke(bookkeeper.clj:105)
    at clojure.core$mapv$fn__6727.invoke(core.clj:6616)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:333)
    at clojure.core$reduce.invoke(core.clj:6518)
    at clojure.core$mapv.invoke(core.clj:6616)
    at onyx.state.bookkeeper.BookieServers.start(bookkeeper.clj:104)
    at com.stuartsierra.component$fn__16299$G__16293__16301.invoke(component.clj:4)
    at com.stuartsierra.component$fn__16299$G__16292__16304.invoke(component.clj:4)
    at clojure.lang.Var.invoke(Var.java:379)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.Var.applyTo(Var.java:700)
    at clojure.core$apply.invoke(core.clj:632)
    at com.stuartsierra.component$try_action.invoke(component.clj:116)
    at com.stuartsierra.component$update_system$fn__16350.invoke(component.clj:138)
    at clojure.lang.ArraySeq.reduce(ArraySeq.java:114)
    at clojure.core$reduce.invoke(core.clj:6518)
    at com.stuartsierra.component$update_system.doInvoke(component.clj:134)
    at clojure.lang.RestFn.invoke(RestFn.java:445)
    at com.stuartsierra.component$start_system.invoke(component.clj:162)
    at onyx.system.OnyxDevelopmentEnv$fn__30707.invoke(system.clj:64)
    at onyx.system$rethrow_component.invoke(system.clj:53)
    at onyx.system.OnyxDevelopmentEnv.start(system.clj:63)
    at onyx.api$start_env.invoke(api.clj:327)
    at onyx.api$start_env.invoke(api.clj:324)
```

The `:onyx.bookkeeper/delete-server-data?` option cleans this up. But in case of an unclean shutdown we still have this issue.

**Comment by stanfea** [comment]
moving issue to main onyx repo
